Repository kthcloud/console, pull requests merged in 2024-05, with the labels that each got.

#241 Support VM v2, Add alert provider, CI/CD TSC check, Beta channel switcher
  .env
  .github/workflows/check-format.yml
  .github/workflows/ts-format-validate.yml
  .gitignore
  README.md
  bun.lockb
  package.json
  src/App.tsx
  src/Router.tsx
  src/api/alert/index.ts
  src/api/alert/types.ts
  src/api/deploy/jobs.ts
  src/api/deploy/teams.ts
  src/api/deploy/teams.tsx
  src/api/deploy/userData.ts
  src/api/deploy/users.ts
  src/api/deploy/v2/gpuGroups.ts
  src/api/deploy/v2/gpuLeases.ts
  src/api/deploy/v2/snapshots.ts
  src/api/deploy/v2/vms.ts
  src/api/deploy/vms.ts
  src/api/sys/index.ts
  src/components/AlertList.tsx
  src/components/JobList.tsx
  src/contexts/AlertContext.tsx
  src/contexts/ResourceContext.tsx
  src/hooks/useAlert.ts
  src/layouts/dashboard/Menu.tsx
  src/layouts/dashboard/index.tsx
  src/locales/en.json
  src/locales/se.json
  src/pages/admin/Admin.tsx
  src/pages/create/CreateDeployment.tsx
  src/pages/create/CreateVm.tsx
  src/pages/create/ZoneSelector.tsx
  src/pages/deploy/Deploy.tsx
  src/pages/edit/DangerZone.tsx
  src/pages/edit/Edit.tsx
  src/pages/edit/deployments/EnvManager.tsx
  src/pages/edit/deployments/GHActions.tsx
  src/pages/edit/deployments/LogsView.tsx
  src/pages/edit/deployments/StorageManager.tsx
  src/pages/edit/vms/GPUManager.tsx
  src/pages/edit/vms/PortManager.tsx
  src/pages/edit/vms/ProxyManager.tsx
  src/pages/edit/vms/SSHString.tsx
  src/pages/edit/vms/Specs.tsx
  src/pages/edit/vms/VMCommands.tsx
  src/pages/gpu/GPU.tsx
  src/pages/inbox/Inbox.tsx
  src/pages/onboarding/Onboarding.tsx
  src/pages/profile/Profile.tsx
  src/pages/profile/ResetOnboarding.tsx
  src/pages/status/Status.tsx
  src/pages/teams/Teams.tsx
  src/types.ts
Labels: enhancement, VM v2

#279 Fix specs being set to min if greater than min
  src/pages/edit/Specs.tsx
Labels: bug

#282 Show replica status, closes #272
  src/locales/en.json
  src/locales/se.json
  src/pages/edit/Edit.tsx
  src/pages/edit/deployments/ReplicaStatus.tsx
Labels: enhancement

#292 Finalize v2 api migration
  .env
  .prettierignore
  bun.lockb
  index.html
  public/favicon/beta/apple-touch-icon.png
  public/favicon/beta/favicon-16x16.png
  public/favicon/beta/favicon-32x32.png
  public/favicon/beta/icon.xcf
  public/favicon/beta/safari-pinned-tab.svg
  src/api/deploy/discover.ts
  src/api/deploy/gpuGroups.ts
  src/api/deploy/gpuLeases.ts
  src/api/deploy/resourceMigrations.ts
  src/api/deploy/snapshots.ts
  src/api/deploy/users.ts
  src/api/deploy/v2/vms.ts
  src/api/deploy/vms.ts
  src/contexts/ResourceContext.tsx
  src/locales/en.json
  src/locales/se.json
  src/pages/admin/Admin.tsx
  src/pages/create/CreateDeployment.tsx
  src/pages/create/CreateVm.tsx
  src/pages/create/ZoneSelector.tsx
  src/pages/deploy/Deploy.tsx
  src/pages/edit/DangerZone.tsx
  src/pages/edit/Edit.tsx
  src/pages/edit/Specs.tsx
  src/pages/edit/deployments/DeploymentCommands.tsx
  src/pages/edit/deployments/DomainManager.tsx
  src/pages/edit/deployments/EnvManager.tsx
  src/pages/edit/deployments/LogsView.tsx
  src/pages/edit/deployments/ReplicaStatus.tsx
  src/pages/edit/deployments/StorageManager.tsx
  src/pages/edit/vms/PortManager.tsx
  src/pages/edit/vms/ProxyManager.tsx
  src/pages/edit/vms/VMCommands.tsx
  src/pages/gpu/GPU.tsx
  src/pages/inbox/Inbox.tsx
  src/pages/landing/components/hero/Hero.tsx
  src/pages/profile/ApiKeys.tsx
  src/pages/status/Status.tsx
  src/pages/teams/Teams.tsx
  src/pages/tiers/Tiers.tsx
  src/types.ts
Labels: enhancement, VM v2
